name: nams # Network Analysis Made Simple
channels:
  - conda-forge
dependencies:
  - python=3.9
  - black
  - ffmpeg
  - gitpython  # used by mkdocs
  - hiveplot
  - ipykernel
  - isort
  - jupyter
  - jupyterlab
  - markdown
  - matplotlib
  - mkdocs
  - mkdocs-material
  - mkdocs-material-extensions  # used by mkdocs-material
  - nbconvert-utils>=0.6
  - nbconvert>=6.0.7
  - nbstripout>=0.3.9
  - networkx>=2.6.3
  - numpy
  - nxviz
  - pandas>=1.0
  - pip
  - pre-commit
  - pygments
  - pyjanitor
  - pymdown-extensions
  - pyprojroot
  - python-louvain
  - rise
  - scipy
  - seaborn
  - tabulate  # used for exporting dataframe as Markdown tables
  - tqdm
  - pip:
    - mknotebooks
