name: nams  # Network Analysis Made Simple
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.6
- matplotlib
- networkx
- scipy
- numpy
- nxviz
- hiveplot
- jupyter
- jupyterlab
- ipykernel
- pandas
- rise
- pip:
    - environment_kernels
