name: nams # Network Analysis Made Simple
channels:
  - defaults
  - conda-forge
  - ericmjl
dependencies:
  - python=3.7
  - matplotlib
  - networkx
  - scipy
  - numpy
  - nxviz
  - hiveplot
  - jupyter=1.0.0
  - jupyterlab=2.2.6
  - ipykernel=5.3.4
  - pandas=1.1.1
  - rise
  - python-louvain
  - tqdm
  - ffmpeg
  - nbstripout=0.3.9
  - pygments
  - pip
  - pyprojroot
  - isort
  - black
  - pyjanitor
  - pre-commit
  - tabulate  # used for exporting dataframe as Markdown tables
  - pip:
      - mkdocs==1.1.2
      - markdown==3.2.2
      - mkdocs-material==5.5.12
      - pymdown-extensions==8.0
      - mknotebooks==0.5.0
      - mkdocstrings==0.13.2
      - git+http://github.com/ericmjl/Network-Analysis-Made-Simple@master
