name: nams  # Network Analysis Made Simple
channels: !!python/tuple
- defaults
- conda-forge
- ericmjl
dependencies:
- matplotlib
- networkx
- scipy
- numpy
- python=3.6
- nxviz
- hiveplot
- jupyter
- pandas
- pip:
    - environment_kernels
