name: nams # Network Analysis Made Simple
channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib
  - networkx
  - scipy
  - numpy
  - hiveplot
  - jupyter
  - jupyterlab
  - ipykernel
  - pandas>=1.0
  - rise
  - python-louvain
  - tqdm
  - ffmpeg
  - nbstripout>=0.3.9
  - pygments
  - pip
  - pyprojroot
  - isort
  - black
  - pyjanitor
  - pre-commit
  - tabulate  # used for exporting dataframe as Markdown tables
  - nbconvert>=6.0.7
  - nbconvert-utils>=0.6
  - pymdown-extensions
  - mkdocs-material
  - mkdocs
  - markdown
  - gitpython  # used by mkdocs
  - mkdocs-material-extensions  # used by mkdocs-material
  - decorator>=5.0.5  # https://github.com/networkx/networkx/issues/4718
  - pip:
    - git+https://github.com/ericmjl/nxviz.git
